'use strict';
const { v4: uuid } = require("uuid");

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
      await queryInterface.bulkInsert("Products", [
        {
          id: uuid(),
          kodebarang: "02.04.041.00.011",
          namabarang: "BLADE W2.0-01-01-03G-03-05",
          image: "https://i.ibb.co/107dKpX/Untitled-design-12.png",
          image2: "https://i.ibb.co/wBzRBXB/Untitled-design-11.png",
          image3: "",
          typebarang: "cluster_2",
          deskripsibarang: "MAXXI Original Spare Parts",
          stockbarang: 10,
          satuanbarang: "pcs",
          price: 25000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "02.13.095.00.069",
          namabarang: "13 TOOTH SPROKET II",
          image: "https://i.ibb.co/4ttPZ1v/Untitled-design.png",
          image2: "https://i.ibb.co/fdNGjJb/Untitled-design-3.png",
          image3: "",
          typebarang: "cluster_2",
          deskripsibarang: "Maxxi Original Sparepart",
          stockbarang: 10,
          satuanbarang: "pcs",
          price: 140000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "02.05.006.02.001",
          namabarang: "CHAIN WHEEL WELD",
          image: "https://i.ibb.co/GcdK9j6/Untitled-design-3.png",
          image2: "https://i.ibb.co/418rhNd/Untitled-design-4.png",
          image3: "",
          typebarang: "cluster_2",
          deskripsibarang: "MAXXI Original Spare Parts",
          stockbarang: 10,
          satuanbarang: "pcs",
          price: 425000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "02.19.004.00.083",
          namabarang: "OSCILLATING BEARING",
          image: "https://i.ibb.co/dthsWWK/Untitled-design.png",
          image2: "https://i.ibb.co/VCwXL0N/Untitled-design-5.png",
          image3: "",
          typebarang: "cluster_2",
          deskripsibarang: "MAXXI Original Spare Parts",
          stockbarang: 10,
          satuanbarang: "pcs",
          price: 240000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "02.20.096.00.054",
          namabarang: "OIL SEAL",
          image: "https://i.ibb.co/SQHGRQx/Untitled-design-1.png",
          image2: "https://i.ibb.co/0DZpcKJ/W1-8-33-06-04-00.png",
          image3: "https://i.ibb.co/jMMjSqy/Untitled-design-6.png",
          typebarang: "cluster_2",
          deskripsibarang: "MAXXI Original Spare Parts",
          stockbarang: 1,
          satuanbarang: "pcs",
          price: 350000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "02.00.000.00.007",
          namabarang: "RICE STRANSPLANTER MAXXI PF-48",
          image: "https://i.ibb.co/hyw6g4q/Rice-Transplanter-MAXXI-PF-48.png",
          image2: "",
          image3: "",
          typebarang: "cluster_1",
          deskripsibarang: "Jumlah Roda:2 buah, Bobot kosong mesin:170 kg, Kebutuhan daya:3,2 kW, Motor Penggerak ; Motor bensin",
          stockbarang: 1,
          satuanbarang: "pcs",
          price: 68000000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "02.00.000.34.001",
          namabarang: "RICE TRANSPLANTER MAXXI TWIN JARWO",
          image: "https://i.ibb.co/p336P0Z/Rice-Transplanter-MAXXI-TWIN-JARWO.png",
          image2: "",
          image3: "",
          typebarang: "cluster_1",
          deskripsibarang: "Jumlah Roda:2 buah, Bobot kosong mesin:180 kg, Kebutuhan daya:3,7 kW, Motor Penggerak:Motor bensin",
          stockbarang: 1,
          satuanbarang: "pcs",
          price: 68000000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "02.00.000.00.004",
          namabarang: "MAXXI J",
          image: "https://i.ibb.co/7brwbZ6/Maxxi-J.png",
          image2: "https://i.ibb.co/NKVm8cp/Maxxi-J-2.png",
          image3: "",
          typebarang: "cluster_1",
          deskripsibarang: "Maxxi Padi J Automatic Engine 45,5 kw yang sangat irit di operasikan untuk memanen padi. ",
          stockbarang: 1,
          satuanbarang: "pcs",
          price: 315000000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "02.33.117.43.003",
          namabarang: "MAXXI BIMO 102",
          image: "https://i.ibb.co/2kcqv97/MAXXI-BIMO-102.png",
          image2: "https://i.ibb.co/gDsfkn6/MAXXI-BIMO-102-2.png",
          image3: "",
          typebarang: "cluster_1",
          deskripsibarang: "Electric Starter, Daya 102 HP, 2600 RPM, Lebar Potong Teoritis 2.180 mm.",
          stockbarang: 1,
          satuanbarang: "pcs",
          price: 3498000000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "",
          namabarang: "MAXXI BIMO 102 SS",
          image: "https://i.ibb.co/mXvjcnc/MAXXI-BIMO-102-ss.png",
          image2: "https://i.ibb.co/gDsfkn6/MAXXI-BIMO-102-2.png",
          image3: "https://i.ibb.co/2kcqv97/MAXXI-BIMO-102.png",
          typebarang: "cluster_1",
          deskripsibarang: "Electric Starter, Daya 102 HP, 2600 RPM, Lebar Potong Teoritis 2.180 mm.",
          stockbarang: 1,
          satuanbarang: "pcs",
          price: 350000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "02.23.116.00.001",
          namabarang: "TRACKTOR MAXXI WD 404",
          image: "https://i.ibb.co/KNHJ8QF/Traktor-MAXXI-WD-404.png",
          image2: "https://i.ibb.co/4TjhLw4/Traktor-MAXXI-WD-404-2.png",
          image3: "",
          typebarang: "cluster_1",
          deskripsibarang: "Kebutuhan daya :29,85 kW/40 HP Motor Penggerak:Diesel Bajak Piringan: a. Jumlah Piringan:3 buah b. Diameter:505 mm",
          stockbarang: 1,
          satuanbarang: "pcs",
          price: 480000000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ]);
    },
  
    async down(queryInterface, Sequelize) {
      await queryInterface.bulkDelete("Products", null, {});
    },
  };
  
